version: '3'
services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: messenger_db
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"

  app:
    restart: always
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data: